import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Hero from "./components/Hero";
import ProductHighlights from "./components/ProductHighlights";
import Footer from "./components/Footer";
import Testimonials from "./components/Testimonials";
import Features from "./components/Features";
import ExclusiveSale from "./components/ExclusiveSale";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar></NavBar>
        {children}
        <Hero></Hero>
        <ProductHighlights></ProductHighlights>
        <ExclusiveSale></ExclusiveSale>
        <Features></Features>
        <Testimonials></Testimonials>
        <Footer></Footer>
      </body>
    </html>
  );
}
